# Generated by Django 5.2.2 on 2025-06-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='places_disponibles',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
