# Generated by Django 5.2.2 on 2025-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paiement_effectué',
            field=models.BooleanField(default=False),
        ),
    ]
